<style  type="text/css"> 
cool {
  width: 100px;
  height: 100px;
  background-color: red;
  position: relative;
  -webkit-animation-name: example; /* Safari 4.0 - 8.0 */
  -webkit-animation-duration: 4s; /* Safari 4.0 - 8.0 */
  -webkit-animation-iteration-count: infinite; /* Safari 4.0 - 8.0 */
  animation-name: example;
  animation-duration: 4s;
  animation-iteration-count: infinite;
}

/* Safari 4.0 - 8.0 */
@-webkit-keyframes example {
  0%   {background-color:red; left:0px; top:0px;}
  25%  {background-color:yellow; left:200px; top:0px;}
  50%  {background-color:blue; left:200px; top:200px;}
  75%  {background-color:green; left:0px; top:200px;}
  100% {background-color:red; left:0px; top:0px;}
}

/* Standard syntax */
@keyframes example {
  0%   {background-color:red; left:0px; top:0px;}
  25%  {background-color:yellow; left:200px; top:0px;}
  50%  {background-color:blue; left:200px; top:200px;}
  75%  {background-color:green; left:0px; top:200px;}
  100% {background-color:red; left:0px; top:0px;}
}


}

</style>

<b><center>
    <span style="font-size: 24pt; line-height: 1.2;">COMS W4111: Introduction to Databases</span><br>
    <span style="font-size: 24pt; line-height: 1.2;">Section 002, Fall 2023</span><br>
</center></b>
<br><br>
<i><center>
<span style="font-size: 20pt; line-height: 1.2;">Lecture 8: Module II, NoSQL, Document DB Examples</span>
</center></i>

__Note:__ Modifying width of cells for wider displays.

# Lecture Material

- The lecture slides contain the lecture material, slides, etc.


- The Jupyter notebook is for running example code and sample applications.

# Environment Setup and Test

## ipython-sql Magic

In [7]:
%load_ext sql

In [8]:
%sql mysql+pymysql://root:dbuserdbuser@localhost

In [9]:
%sql select * from db_book.student limit 10

 * mysql+pymysql://root:***@localhost
10 rows affected.

[('00128', 'Zhang', 'Comp. Sci.', Decimal('102')),
 ('12345', 'Shankar', 'Comp. Sci.', Decimal('32')),
 ('19991', 'Brandt', 'History', Decimal('80')),
 ('23121', 'Chavez', 'Finance', Decimal('110')),
 ('44553', 'Peltier', 'Physics', Decimal('56')),
 ('45678', 'Levy', 'Physics', Decimal('46')),
 ('54321', 'Williams', 'Comp. Sci.', Decimal('54')),
 ('55739', 'Sanchez', 'Music', Decimal('38')),
 ('70557', 'Snow', 'Physics', Decimal('0')),
 ('76543', 'Brown', 'Comp. Sci.', Decimal('58'))]

## PyMySQL

In [10]:
import pymysql

__Note to DFF:__ Explain some of the concepts below:
1. Cursors and cursorclass
2. Autocommit
3. Why we get an array back

In [11]:
conn = pymysql.connect(
    host="localhost",
    user="root",
    password="dbuserdbuser",
    cursorclass=pymysql.cursors.DictCursor,
    autocommit=True)

In [12]:
cur = conn.cursor()
res = cur.execute("select * from db_book.student limit 10")
res = cur.fetchall()

In [13]:
res

[{'ID': '00128',
  'name': 'Zhang',
  'dept_name': 'Comp. Sci.',
  'tot_cred': Decimal('102')},
 {'ID': '12345',
  'name': 'Shankar',
  'dept_name': 'Comp. Sci.',
  'tot_cred': Decimal('32')},
 {'ID': '19991',
  'name': 'Brandt',
  'dept_name': 'History',
  'tot_cred': Decimal('80')},
 {'ID': '23121',
  'name': 'Chavez',
  'dept_name': 'Finance',
  'tot_cred': Decimal('110')},
 {'ID': '44553',
  'name': 'Peltier',
  'dept_name': 'Physics',
  'tot_cred': Decimal('56')},
 {'ID': '45678',
  'name': 'Levy',
  'dept_name': 'Physics',
  'tot_cred': Decimal('46')},
 {'ID': '54321',
  'name': 'Williams',
  'dept_name': 'Comp. Sci.',
  'tot_cred': Decimal('54')},
 {'ID': '55739',
  'name': 'Sanchez',
  'dept_name': 'Music',
  'tot_cred': Decimal('38')},
 {'ID': '70557',
  'name': 'Snow',
  'dept_name': 'Physics',
  'tot_cred': Decimal('0')},
 {'ID': '76543',
  'name': 'Brown',
  'dept_name': 'Comp. Sci.',
  'tot_cred': Decimal('58')}]

## Pandas and SQLAlchemy

In [14]:
import pandas

In [15]:
import sqlalchemy

In [16]:
engine = sqlalchemy.create_engine("mysql+pymysql://root:dbuserdbuser@localhost")

In [17]:
df = pandas.read_sql("select * from db_book.student limit 10", con=engine)

In [18]:
df

      ID      name   dept_name  tot_cred
0  00128     Zhang  Comp. Sci.     102.0
1  12345   Shankar  Comp. Sci.      32.0
2  19991    Brandt     History      80.0
3  23121    Chavez     Finance     110.0
4  44553   Peltier     Physics      56.0
5  45678      Levy     Physics      46.0
6  54321  Williams  Comp. Sci.      54.0
7  55739   Sanchez       Music      38.0
8  70557      Snow     Physics       0.0
9  76543     Brown  Comp. Sci.      58.0

# Document vs Relational

## Concepts

- Let's remind ourselves about ```classic models.```


- We used in previous examples.

| <img src="classic-models.png"> |
| :---: |
| __Classic Models Database__ |

- An online form for displaying and editing an order might looks something like ... ...

<img src="./customer-form.jpg">

- Getting the __data_ is relatively easy in SQL.

In [19]:
%%sql

use classicmodels;

with ordersAll as (
    select * from
        orders join orderdetails using(orderNumber)
)
select * from customers join ordersAll using(customerNumber) where customerNumber=103;

 * mysql+pymysql://root:***@localhost
0 rows affected.
7 rows affected.

[(103, 'Atelier graphique', 'Schmitt', 'Carine ', '40.32.2555', '54, rue Royale', None, 'Nantes', None, '44000', 'France', 1370, Decimal('21000.00'), 10123, datetime.date(2003, 5, 20), datetime.date(2003, 5, 29), datetime.date(2003, 5, 22), 'Shipped', None, 'S18_1589', 26, Decimal('120.71'), 2),
 (103, 'Atelier graphique', 'Schmitt', 'Carine ', '40.32.2555', '54, rue Royale', None, 'Nantes', None, '44000', 'France', 1370, Decimal('21000.00'), 10123, datetime.date(2003, 5, 20), datetime.date(2003, 5, 29), datetime.date(2003, 5, 22), 'Shipped', None, 'S18_2870', 46, Decimal('114.84'), 3),
 (103, 'Atelier graphique', 'Schmitt', 'Carine ', '40.32.2555', '54, rue Royale', None, 'Nantes', None, '44000', 'France', 1370, Decimal('21000.00'), 10123, datetime.date(2003, 5, 20), datetime.date(2003, 5, 29), datetime.date(2003, 5, 22), 'Shipped', None, 'S18_3685', 34, Decimal('117.26'), 4),
 (103, 'Atelier graphique', 'Schmitt', 'Carine ', '40.32.2555', '54, rue Royale', None, 'Nantes', None, '44000', 'France', 1370, Decimal('21000.00'), 10123, datetime.date(2003, 5, 20), datetime.date(2003, 5, 29), datetime.date(2003, 5, 22), 'Shipped', None, 'S24_1628', 50, Decimal('43.27'), 1),
 (103, 'Atelier graphique', 'Schmitt', 'Carine ', '40.32.2555', '54, rue Royale', None, 'Nantes', None, '44000', 'France', 1370, Decimal('21000.00'), 10298, datetime.date(2004, 9, 27), datetime.date(2004, 10, 5), datetime.date(2004, 10, 1), 'Shipped', None, 'S10_2016', 39, Decimal('105.86'), 1),
 (103, 'Atelier graphique', 'Schmitt', 'Carine ', '40.32.2555', '54, rue Royale', None, 'Nantes', None, '44000', 'France', 1370, Decimal('21000.00'), 10298, datetime.date(2004, 9, 27), datetime.date(2004, 10, 5), datetime.date(2004, 10, 1), 'Shipped', None, 'S18_2625', 32, Decimal('60.57'), 2),
 (103, 'Atelier graphique', 'Schmitt', 'Carine ', '40.32.2555', '54, rue Royale', None, 'Nantes', None, '44000', 'France', 1370, Decimal('21000.00'), 10345, datetime.date(2004, 11, 25), datetime.date(2004, 12, 1), datetime.date(2004, 11, 26), 'Shipped', None, 'S24_2022', 43, Decimal('38.98'), 1)]

- But, the __shape__ or __format__ of this data is different from how I want to display/edit it.


- The relational model, in this case, does not match the user's __logical model.__ This is a __data model impedance mismatch.__


- A document model with native support for nesting, multi-valued attributes, composite attributes, etc. is a better match.

<img src="./ui-and-data.jpg">

- We can transform the relational data into a document model.

In [20]:
customerData = %sql select * from customers;

 * mysql+pymysql://root:***@localhost
122 rows affected.

In [21]:
customerData

[(103, 'Atelier graphique', 'Schmitt', 'Carine ', '40.32.2555', '54, rue Royale', None, 'Nantes', None, '44000', 'France', 1370, Decimal('21000.00')),
 (112, 'Signal Gift Stores', 'King', 'Jean', '7025551838', '8489 Strong St.', None, 'Las Vegas', 'NV', '83030', 'USA', 1166, Decimal('71800.00')),
 (114, 'Australian Collectors, Co.', 'Ferguson', 'Peter', '03 9520 4555', '636 St Kilda Road', 'Level 3', 'Melbourne', 'Victoria', '3004', 'Australia', 1611, Decimal('117300.00')),
 (119, 'La Rochelle Gifts', 'Labrune', 'Janine ', '40.67.8555', '67, rue des Cinquante Otages', None, 'Nantes', None, '44000', 'France', 1370, Decimal('118200.00')),
 (121, 'Baane Mini Imports', 'Bergulfsen', 'Jonas ', '07-98 9555', 'Erling Skakkes gate 78', None, 'Stavern', None, '4110', 'Norway', 1504, Decimal('81700.00')),
 (124, 'Mini Gifts Distributors Ltd.', 'Nelson', 'Susan', '4155551450', '5677 Strong St.', None, 'San Rafael', 'CA', '97562', 'USA', 1165, Decimal('210500.00')),
 (125, 'Havel & Zbyszek Co', 'Piestrzeniewicz', 'Zbyszek ', '(26) 642-7555', 'ul. Filtrowa 68', None, 'Warszawa', None, '01-012', 'Poland', None, Decimal('0.00')),
 (128, 'Blauer See Auto, Co.', 'Keitel', 'Roland', '+49 69 66 90 2555', 'Lyonerstr. 34', None, 'Frankfurt', None, '60528', 'Germany', 1504, Decimal('59700.00')),
 (129, 'Mini Wheels Co.', 'Murphy', 'Julie', '6505555787', '5557 North Pendale Street', None, 'San Francisco', 'CA', '94217', 'USA', 1165, Decimal('64600.00')),
 (131, 'Land of Toys Inc.', 'Lee', 'Kwai', '2125557818', '897 Long Airport Avenue', None, 'NYC', 'NY', '10022', 'USA', 1323, Decimal('114900.00')),
 (141, 'Euro+ Shopping Channel', 'Freyre', 'Diego ', '(91) 555 94 44', 'C/ Moralzarzal, 86', None, 'Madrid', None, '28034', 'Spain', 1370, Decimal('227600.00')),
 (144, 'Volvo Model Replicas, Co', 'Berglund', 'Christina ', '0921-12 3555', 'Berguvsvägen  8', None, 'Luleå', None, 'S-958 22', 'Sweden', 1504, Decimal('53100.00')),
 (145, 'Danish Wholesale Imports', 'Petersen', 'Jytte ', '31 12 3555', 'Vinbæltet 34', None, 'Kobenhavn', None, '1734', 'Denmark', 1401, Decimal('83400.00')),
 (146, 'Saveley & Henriot, Co.', 'Saveley', 'Mary ', '78.32.5555', '2, rue du Commerce', None, 'Lyon', None, '69004', 'France', 1337, Decimal('123900.00')),
 (148, 'Dragon Souveniers, Ltd.', 'Natividad', 'Eric', '+65 221 7555', 'Bronz Sok.', 'Bronz Apt. 3/6 Tesvikiye', 'Singapore', None, '079903', 'Singapore', 1621, Decimal('103800.00')),
 (151, 'Muscle Machine Inc', 'Young', 'Jeff', '2125557413', '4092 Furth Circle', 'Suite 400', 'NYC', 'NY', '10022', 'USA', 1286, Decimal('138500.00')),
 (157, 'Diecast Classics Inc.', 'Leong', 'Kelvin', '2155551555', '7586 Pompton St.', None, 'Allentown', 'PA', '70267', 'USA', 1216, Decimal('100600.00')),
 (161, 'Technics Stores Inc.', 'Hashimoto', 'Juri', '6505556809', '9408 Furth Circle', None, 'Burlingame', 'CA', '94217', 'USA', 1165, Decimal('84600.00')),
 (166, 'Handji Gifts& Co', 'Victorino', 'Wendy', '+65 224 1555', '106 Linden Road Sandown', '2nd Floor', 'Singapore', None, '069045', 'Singapore', 1612, Decimal('97900.00')),
 (167, 'Herkku Gifts', 'Oeztan', 'Veysel', '+47 2267 3215', 'Brehmen St. 121', 'PR 334 Sentrum', 'Bergen', None, 'N 5804', 'Norway  ', 1504, Decimal('96800.00')),
 (168, 'American Souvenirs Inc', 'Franco', 'Keith', '2035557845', '149 Spinnaker Dr.', 'Suite 101', 'New Haven', 'CT', '97823', 'USA', 1286, Decimal('0.00')),
 (169, 'Porto Imports Co.', 'de Castro', 'Isabel ', '(1) 356-5555', 'Estrada da saúde n. 58', None, 'Lisboa', None, '1756', 'Portugal', None, Decimal('0.00')),
 (171, 'Daedalus Designs Imports', 'Rancé', 'Martine ', '20.16.1555', '184, chaussée de Tournai', None, 'Lille', None, '59000', 'France', 1370, Decimal('82900.00')),
 (172, "La Corne D'abondance, Co.", 'Bertrand', 'Marie', '(1) 42.34.2555', '265, boulevard Charonne', None, 'Paris', None, '75012', 'France', 1337, Decimal('84300.00')),
 (173, 'Cambridge Collectables Co.', 'Tseng', 'Jerry', '6175555555', '4658 Baden Av.', None, 'Cambridge', 'MA', '51247', 'USA', 1188, Decimal('43400.00')),
 (175, 'Gift Depot Inc.', 'King', 'Julie', '2035552570', '25593 South Bay Ln.', None, 'Bridgewater', 'CT', '97562', 'USA', 1323, Decimal('84300.00')),
 (177, 'Osaka Souveniers Co.', 'Kentary', 'Mory', '+81 06 6342 5555', '1-6-20 Dojima', None, 'Kita-ku', 'Osaka', ' 530-0003', 'Japan', 1621, Decimal('81200.00')),
 (181, 'Vitachrome Inc.', 'Frick', 'Michael', '2125551500', '2678 Kingston Rd.', 'Suite 101', 'NYC', 'NY', '10022', 'USA', 1286, Decimal('76400.00')),
 (186, 'Toys of Finland, Co.', 'Karttunen', 'Matti', '90-224 8555', 'Keskuskatu 45', None, 'Helsinki', None, '21240', 'Finland', 1501, Decimal('96500.00')),
 (187, 'AV Stores, Co.', 'Ashworth', 'Rachel', '(171) 555-1555', 'Fauntleroy Circus', None, 'Manchester', None, 'EC2 5NT', 'UK', 1501, Decimal('136800.00')),
 (189, 'Clover Collections, Co.', 'Cassidy', 'Dean', '+353 1862 1555', '25 Maiden Lane', 'Floor No. 4', 'Dublin', None, '2', 'Ireland', 1504, Decimal('69400.00')),
 (198, 'Auto-Moto Classics Inc.', 'Taylor', 'Leslie', '6175558428', '16780 Pompton St.', None, 'Brickhaven', 'MA', '58339', 'USA', 1216, Decimal('23000.00')),
 (201, 'UK Collectables, Ltd.', 'Devon', 'Elizabeth', '(171) 555-2282', '12, Berkeley Gardens Blvd', None, 'Liverpool', None, 'WX1 6LT', 'UK', 1501, Decimal('92700.00')),
 (202, 'Canadian Gift Exchange Network', 'Tamuri', 'Yoshi ', '(604) 555-3392', '1900 Oak St.', None, 'Vancouver', 'BC', 'V3F 2K1', 'Canada', 1323, Decimal('90300.00')),
 (204, 'Online Mini Collectables', 'Barajas', 'Miguel', '6175557555', '7635 Spinnaker Dr.', None, 'Brickhaven', 'MA', '58339', 'USA', 1188, Decimal('68700.00')),
 (205, 'Toys4GrownUps.com', 'Young', 'Julie', '6265557265', '78934 Hillside Dr.', None, 'Pasadena', 'CA', '90003', 'USA', 1166, Decimal('90700.00')),
 (206, 'Asian Shopping Network, Co', 'Walker', 'Brydey', '+612 9411 1555', 'Suntec Tower Three', '8 Temasek', 'Singapore', None, '038988', 'Singapore', None, Decimal('0.00')),
 (209, 'Mini Caravy', 'Citeaux', 'Frédérique ', '88.60.1555', '24, place Kléber', None, 'Strasbourg', None, '67000', 'France', 1370, Decimal('53800.00')),
 (211, 'King Kong Collectables, Co.', 'Gao', 'Mike', '+852 2251 1555', 'Bank of China Tower', '1 Garden Road', 'Central Hong Kong', None, None, 'Hong Kong', 1621, Decimal('58600.00')),
 (216, 'Enaco Distributors', 'Saavedra', 'Eduardo ', '(93) 203 4555', 'Rambla de Cataluña, 23', None, 'Barcelona', None, '08022', 'Spain', 1702, Decimal('60300.00')),
 (219, 'Boards & Toys Co.', 'Young', 'Mary', '3105552373', '4097 Douglas Av.', None, 'Glendale', 'CA', '92561', 'USA', 1166, Decimal('11000.00')),
 (223, 'Natürlich Autos', 'Kloss', 'Horst ', '0372-555188', 'Taucherstraße 10', None, 'Cunewalde', None, '01307', 'Germany', None, Decimal('0.00')),
 (227, 'Heintze Collectables', 'Ibsen', 'Palle', '86 21 3555', 'Smagsloget 45', None, 'Århus', None, '8200', 'Denmark', 1401, Decimal('120800.00')),
 (233, 'Québec Home Shopping Network', 'Fresnière', 'Jean ', '(514) 555-8054', '43 rue St. Laurent', None, 'Montréal', 'Québec', 'H1J 1C3', 'Canada', 1286, Decimal('48700.00')),
 (237, 'ANG Resellers', 'Camino', 'Alejandra ', '(91) 745 6555', 'Gran Vía, 1', None, 'Madrid', None, '28001', 'Spain', None, Decimal('0.00')),
 (239, 'Collectable Mini Designs Co.', 'Thompson', 'Valarie', '7605558146', '361 Furth Circle', None, 'San Diego', 'CA', '91217', 'USA', 1166, Decimal('105000.00')),
 (240, 'giftsbymail.co.uk', 'Bennett', 'Helen ', '(198) 555-8888', 'Garden House', 'Crowther Way 23', 'Cowes', 'Isle of Wight', 'PO31 7PJ', 'UK', 1501, Decimal('93900.00')),
 (242, 'Alpha Cognac', 'Roulet', 'Annette ', '61.77.6555', '1 rue Alsace-Lorraine', None, 'Toulouse', None, '31000', 'France', 1370, Decimal('61100.00')),
 (247, 'Messner Shopping Network', 'Messner', 'Renate ', '069-0555984', 'Magazinweg 7', None, 'Frankfurt', None, '60528', 'Germany', None, Decimal('0.00')),
 (249, 'Amica Models & Co.', 'Accorti', 'Paolo ', '011-4988555', 'Via Monte Bianco 34', None, 'Torino', None, '10100', 'Italy', 1401, Decimal('113000.00')),
 (250, 'Lyon Souveniers', 'Da Silva', 'Daniel', '+33 1 46 62 7555', '27 rue du Colonel Pierre Avia', None, 'Paris', None, '75508', 'France', 1337, Decimal('68100.00')),
 (256, 'Auto Associés & Cie.', 'Tonini', 'Daniel ', '30.59.8555', "67, avenue de l'Europe", None, 'Versailles', None, '78000', 'France', 1370, Decimal('77900.00')),
 (259, 'Toms Spezialitäten, Ltd', 'Pfalzheim', 'Henriette ', '0221-5554327', 'Mehrheimerstr. 369', None, 'Köln', None, '50739', 'Germany', 1504, Decimal('120400.00')),
 (260, 'Royal Canadian Collectables, Ltd.', 'Lincoln', 'Elizabeth ', '(604) 555-4555', '23 Tsawassen Blvd.', None, 'Tsawassen', 'BC', 'T2F 8M4', 'Canada', 1323, Decimal('89600.00')),
 (273, 'Franken Gifts, Co', 'Franken', 'Peter ', '089-0877555', 'Berliner Platz 43', None, 'München', None, '80805', 'Germany', None, Decimal('0.00')),
 (276, "Anna's Decorations, Ltd", "O'Hara", 'Anna', '02 9936 8555', '201 Miller Street', 'Level 15', 'North Sydney', 'NSW', '2060', 'Australia', 1611, Decimal('107800.00')),
 (278, 'Rovelli Gifts', 'Rovelli', 'Giovanni ', '035-640555', 'Via Ludovico il Moro 22', None, 'Bergamo', None, '24100', 'Italy', 1401, Decimal('119600.00')),
 (282, 'Souveniers And Things Co.', 'Huxley', 'Adrian', '+61 2 9495 8555', 'Monitor Money Building', '815 Pacific Hwy', 'Chatswood', 'NSW', '2067', 'Australia', 1611, Decimal('93300.00')),
 (286, "Marta's Replicas Co.", 'Hernandez', 'Marta', '6175558555', '39323 Spinnaker Dr.', None, 'Cambridge', 'MA', '51247', 'USA', 1216, Decimal('123700.00')),
 (293, 'BG&E Collectables', 'Harrison', 'Ed', '+41 26 425 50 01', 'Rte des Arsenaux 41 ', None, 'Fribourg', None, '1700', 'Switzerland', None, Decimal('0.00')),
 (298, 'Vida Sport, Ltd', 'Holz', 'Mihael', '0897-034555', 'Grenzacherweg 237', None, 'Genève', None, '1203', 'Switzerland', 1702, Decimal('141300.00')),
 (299, 'Norway Gifts By Mail, Co.', 'Klaeboe', 'Jan', '+47 2212 1555', 'Drammensveien 126A', 'PB 211 Sentrum', 'Oslo', None, 'N 0106', 'Norway  ', 1504, Decimal('95100.00')),
 (303, 'Schuyler Imports', 'Schuyler', 'Bradley', '+31 20 491 9555', 'Kingsfordweg 151', None, 'Amsterdam', None, '1043 GR', 'Netherlands', None, Decimal('0.00')),
 (307, 'Der Hund Imports', 'Andersen', 'Mel', '030-0074555', 'Obere Str. 57', None, 'Berlin', None, '12209', 'Germany', None, Decimal('0.00')),
 (311, 'Oulu Toy Supplies, Inc.', 'Koskitalo', 'Pirkko', '981-443655', 'Torikatu 38', None, 'Oulu', None, '90110', 'Finland', 1501, Decimal('90500.00')),
 (314, 'Petit Auto', 'Dewey', 'Catherine ', '(02) 5554 67', 'Rue Joseph-Bens 532', None, 'Bruxelles', None, 'B-1180', 'Belgium', 1401, Decimal('79900.00')),
 (319, 'Mini Classics', 'Frick', 'Steve', '9145554562', '3758 North Pendale Street', None, 'White Plains', 'NY', '24067', 'USA', 1323, Decimal('102700.00')),
 (320, 'Mini Creations Ltd.', 'Huang', 'Wing', '5085559555', '4575 Hillside Dr.', None, 'New Bedford', 'MA', '50553', 'USA', 1188, Decimal('94500.00')),
 (321, 'Corporate Gift Ideas Co.', 'Brown', 'Julie', '6505551386', '7734 Strong St.', None, 'San Francisco', 'CA', '94217', 'USA', 1165, Decimal('105000.00')),
 (323, 'Down Under Souveniers, Inc', 'Graham', 'Mike', '+64 9 312 5555', '162-164 Grafton Road', 'Level 2', 'Auckland  ', None, None, 'New Zealand', 1612, Decimal('88000.00')),
 (324, 'Stylish Desk Decors, Co.', 'Brown', 'Ann ', '(171) 555-0297', '35 King George', None, 'London', None, 'WX3 6FW', 'UK', 1501, Decimal('77000.00')),
 (328, 'Tekni Collectables Inc.', 'Brown', 'William', '2015559350', '7476 Moss Rd.', None, 'Newark', 'NJ', '94019', 'USA', 1323, Decimal('43000.00')),
 (333, 'Australian Gift Network, Co', 'Calaghan', 'Ben', '61-7-3844-6555', '31 Duncan St. West End', None, 'South Brisbane', 'Queensland', '4101', 'Australia', 1611, Decimal('51600.00')),
 (334, 'Suominen Souveniers', 'Suominen', 'Kalle', '+358 9 8045 555', 'Software Engineering Center', 'SEC Oy', 'Espoo', None, 'FIN-02271', 'Finland', 1501, Decimal('98800.00')),
 (335, 'Cramer Spezialitäten, Ltd', 'Cramer', 'Philip ', '0555-09555', 'Maubelstr. 90', None, 'Brandenburg', None, '14776', 'Germany', None, Decimal('0.00')),
 (339, 'Classic Gift Ideas, Inc', 'Cervantes', 'Francisca', '2155554695', '782 First Street', None, 'Philadelphia', 'PA', '71270', 'USA', 1188, Decimal('81100.00')),
 (344, 'CAF Imports', 'Fernandez', 'Jesus', '+34 913 728 555', 'Merchants House', "27-30 Merchant's Quay", 'Madrid', None, '28023', 'Spain', 1702, Decimal('59600.00')),
 (347, "Men 'R' US Retailers, Ltd.", 'Chandler', 'Brian', '2155554369', '6047 Douglas Av.', None, 'Los Angeles', 'CA', '91003', 'USA', 1166, Decimal('57700.00')),
 (348, 'Asian Treasures, Inc.', 'McKenna', 'Patricia ', '2967 555', '8 Johnstown Road', None, 'Cork', 'Co. Cork', None, 'Ireland', None, Decimal('0.00')),
 (350, 'Marseille Mini Autos', 'Lebihan', 'Laurence ', '91.24.4555', '12, rue des Bouchers', None, 'Marseille', None, '13008', 'France', 1337, Decimal('65000.00')),
 (353, 'Reims Collectables', 'Henriot', 'Paul ', '26.47.1555', "59 rue de l'Abbaye", None, 'Reims', None, '51100', 'France', 1337, Decimal('81100.00')),
 (356, 'SAR Distributors, Co', 'Kuger', 'Armand', '+27 21 550 3555', '1250 Pretorius Street', None, 'Hatfield', 'Pretoria', '0028', 'South Africa', None, Decimal('0.00')),
 (357, 'GiftsForHim.com', 'MacKinlay', 'Wales', '64-9-3763555', '199 Great North Road', None, 'Auckland', None, None, 'New Zealand', 1612, Decimal('77700.00')),
 (361, 'Kommission Auto', 'Josephs', 'Karin', '0251-555259', 'Luisenstr. 48', None, 'Münster', None, '44087', 'Germany', None, Decimal('0.00')),
 (362, 'Gifts4AllAges.com', 'Yoshido', 'Juri', '6175559555', '8616 Spinnaker Dr.', None, 'Boston', 'MA', '51003', 'USA', 1216, Decimal('41900.00')),
 (363, 'Online Diecast Creations Co.', 'Young', 'Dorothy', '6035558647', '2304 Long Airport Avenue', None, 'Nashua', 'NH', '62005', 'USA', 1216, Decimal('114200.00')),
 (369, 'Lisboa Souveniers, Inc', 'Rodriguez', 'Lino ', '(1) 354-2555', 'Jardim das rosas n. 32', None, 'Lisboa', None, '1675', 'Portugal', None, Decimal('0.00')),
 (376, 'Precious Collectables', 'Urs', 'Braun', '0452-076555', 'Hauptstr. 29', None, 'Bern', None, '3012', 'Switzerland', 1702, Decimal('0.00')),
 (379, 'Collectables For Less Inc.', 'Nelson', 'Allen', '6175558555', '7825 Douglas Av.', None, 'Brickhaven', 'MA', '58339', 'USA', 1188, Decimal('70700.00')),
 (381, 'Royale Belge', 'Cartrain', 'Pascale ', '(071) 23 67 2555', 'Boulevard Tirou, 255', None, 'Charleroi', None, 'B-6000', 'Belgium', 1401, Decimal('23500.00')),
 (382, 'Salzburg Collectables', 'Pipps', 'Georg ', '6562-9555', 'Geislweg 14', None, 'Salzburg', None, '5020', 'Austria', 1401, Decimal('71700.00')),
 (385, 'Cruz & Sons Co.', 'Cruz', 'Arnold', '+63 2 555 3587', '15 McCallum Street', 'NatWest Center #13-03', 'Makati City', None, '1227 MM', 'Philippines', 1621, Decimal('81500.00')),
 (386, "L'ordine Souveniers", 'Moroni', 'Maurizio ', '0522-556555', 'Strada Provinciale 124', None, 'Reggio Emilia', None, '42100', 'Italy', 1401, Decimal('121400.00')),
 (398, 'Tokyo Collectables, Ltd', 'Shimamura', 'Akiko', '+81 3 3584 0555', '2-2-8 Roppongi', None, 'Minato-ku', 'Tokyo', '106-0032', 'Japan', 1621, Decimal('94400.00')),
 (406, 'Auto Canal+ Petit', 'Perrier', 'Dominique', '(1) 47.55.6555', '25, rue Lauriston', None, 'Paris', None, '75016', 'France', 1337, Decimal('95000.00')),
 (409, 'Stuttgart Collectable Exchange', 'Müller', 'Rita ', '0711-555361', 'Adenauerallee 900', None, 'Stuttgart', None, '70563', 'Germany', None, Decimal('0.00')),
 (412, 'Extreme Desk Decorations, Ltd', 'McRoy', 'Sarah', '04 499 9555', '101 Lambton Quay', 'Level 11', 'Wellington', None, None, 'New Zealand', 1612, Decimal('86800.00')),
 (415, 'Bavarian Collectables Imports, Co.', 'Donnermeyer', 'Michael', ' +49 89 61 08 9555', 'Hansastr. 15', None, 'Munich', None, '80686', 'Germany', 1504, Decimal('77000.00')),
 (424, 'Classic Legends Inc.', 'Hernandez', 'Maria', '2125558493', '5905 Pompton St.', 'Suite 750', 'NYC', 'NY', '10022', 'USA', 1286, Decimal('67500.00')),
 (443, 'Feuer Online Stores, Inc', 'Feuer', 'Alexander ', '0342-555176', 'Heerstr. 22', None, 'Leipzig', None, '04179', 'Germany', None, Decimal('0.00')),
 (447, 'Gift Ideas Corp.', 'Lewis', 'Dan', '2035554407', '2440 Pompton St.', None, 'Glendale', 'CT', '97561', 'USA', 1323, Decimal('49700.00')),
 (448, 'Scandinavian Gift Ideas', 'Larsson', 'Martha', '0695-34 6555', 'Åkergatan 24', None, 'Bräcke', None, 'S-844 67', 'Sweden', 1504, Decimal('116400.00')),
 (450, 'The Sharp Gifts Warehouse', 'Frick', 'Sue', '4085553659', '3086 Ingle Ln.', None, 'San Jose', 'CA', '94217', 'USA', 1165, Decimal('77600.00')),
 (452, 'Mini Auto Werke', 'Mendel', 'Roland ', '7675-3555', 'Kirchgasse 6', None, 'Graz', None, '8010', 'Austria', 1401, Decimal('45300.00')),
 (455, 'Super Scale Inc.', 'Murphy', 'Leslie', '2035559545', '567 North Pendale Street', None, 'New Haven', 'CT', '97823', 'USA', 1286, Decimal('95400.00')),
 (456, 'Microscale Inc.', 'Choi', 'Yu', '2125551957', '5290 North Pendale Street', 'Suite 200', 'NYC', 'NY', '10022', 'USA', 1286, Decimal('39800.00')),
 (458, 'Corrida Auto Replicas, Ltd', 'Sommer', 'Martín ', '(91) 555 22 82', 'C/ Araquil, 67', None, 'Madrid', None, '28023', 'Spain', 1702, Decimal('104600.00')),
 (459, 'Warburg Exchange', 'Ottlieb', 'Sven ', '0241-039123', 'Walserweg 21', None, 'Aachen', None, '52066', 'Germany', None, Decimal('0.00')),
 (462, 'FunGiftIdeas.com', 'Benitez', 'Violeta', '5085552555', '1785 First Street', None, 'New Bedford', 'MA', '50553', 'USA', 1216, Decimal('85800.00')),
 (465, 'Anton Designs, Ltd.', 'Anton', 'Carmen', '+34 913 728555', 'c/ Gobelas, 19-1 Urb. La Florida', None, 'Madrid', None, '28023', 'Spain', None, Decimal('0.00')),
 (471, 'Australian Collectables, Ltd', 'Clenahan', 'Sean', '61-9-3844-6555', '7 Allen Street', None, 'Glen Waverly', 'Victoria', '3150', 'Australia', 1611, Decimal('60300.00')),
 (473, 'Frau da Collezione', 'Ricotti', 'Franco', '+39 022515555', '20093 Cologno Monzese', 'Alessandro Volta 16', 'Milan', None, None, 'Italy', 1401, Decimal('34800.00')),
 (475, 'West Coast Collectables Co.', 'Thompson', 'Steve', '3105553722', '3675 Furth Circle', None, 'Burbank', 'CA', '94019', 'USA', 1166, Decimal('55400.00')),
 (477, 'Mit Vergnügen & Co.', 'Moos', 'Hanna ', '0621-08555', 'Forsterstr. 57', None, 'Mannheim', None, '68306', 'Germany', None, Decimal('0.00')),
 (480, 'Kremlin Collectables, Co.', 'Semenov', 'Alexander ', '+7 812 293 0521', '2 Pobedy Square', None, 'Saint Petersburg', None, '196143', 'Russia', None, Decimal('0.00')),
 (481, 'Raanan Stores, Inc', 'Altagar,G M', 'Raanan', '+ 972 9 959 8555', '3 Hagalim Blv.', None, 'Herzlia', None, '47625', 'Israel', None, Decimal('0.00')),
 (484, 'Iberia Gift Imports, Corp.', 'Roel', 'José Pedro ', '(95) 555 82 82', 'C/ Romero, 33', None, 'Sevilla', None, '41101', 'Spain', 1702, Decimal('65700.00')),
 (486, 'Motor Mint Distributors Inc.', 'Salazar', 'Rosa', '2155559857', '11328 Douglas Av.', None, 'Philadelphia', 'PA', '71270', 'USA', 1323, Decimal('72600.00')),
 (487, 'Signal Collectibles Ltd.', 'Taylor', 'Sue', '4155554312', '2793 Furth Circle', None, 'Brisbane', 'CA', '94217', 'USA', 1165, Decimal('60300.00')),
 (489, 'Double Decker Gift Stores, Ltd', 'Smith', 'Thomas ', '(171) 555-7555', '120 Hanover Sq.', None, 'London', None, 'WA1 1DP', 'UK', 1501, Decimal('43300.00')),
 (495, 'Diecast Collectables', 'Franco', 'Valarie', '6175552555', '6251 Ingle Ln.', None, 'Boston', 'MA', '51003', 'USA', 1188, Decimal('85100.00')),
 (496, "Kelly's Gift Shop", 'Snowden', 'Tony', '+64 9 5555500', "Arenales 1938 3'A'", None, 'Auckland  ', None, None, 'New Zealand', 1612, Decimal('110000.00'))]

In [22]:
customers = []

for c in customerData:
    new_c = dict()
    new_c["number"] = c["customerNumber"]
    new_c["name"] = c["customerName"]
    new_c["contact"] = {
        "lastName": c["contactLastName"],
        "firstName": c["contactFirstName"],
        "phone": c["phone"]
    }
    new_c["address"] = {
        "line1": c["addressLine1"],
        "line2": c["addressLine2"],
        "city": c["city"],
        "state": c["state"],
        "country": c["country"],
        "postalCode": c["postalCode"]
    }
    customers.append(new_c)

In [23]:
customers

[{'number': 103,
  'name': 'Atelier graphique',
  'contact': {'lastName': 'Schmitt',
   'firstName': 'Carine ',
   'phone': '40.32.2555'},
  'address': {'line1': '54, rue Royale',
   'line2': None,
   'city': 'Nantes',
   'state': None,
   'country': 'France',
   'postalCode': '44000'}},
 {'number': 112,
  'name': 'Signal Gift Stores',
  'contact': {'lastName': 'King', 'firstName': 'Jean', 'phone': '7025551838'},
  'address': {'line1': '8489 Strong St.',
   'line2': None,
   'city': 'Las Vegas',
   'state': 'NV',
   'country': 'USA',
   'postalCode': '83030'}},
 {'number': 114,
  'name': 'Australian Collectors, Co.',
  'contact': {'lastName': 'Ferguson',
   'firstName': 'Peter',
   'phone': '03 9520 4555'},
  'address': {'line1': '636 St Kilda Road',
   'line2': 'Level 3',
   'city': 'Melbourne',
   'state': 'Victoria',
   'country': 'Australia',
   'postalCode': '3004'}},
 {'number': 119,
  'name': 'La Rochelle Gifts',
  'contact': {'lastName': 'Labrune',
   'firstName': 'Janine ',
   'phone': '40.67.8555'},
  'address': {'line1': '67, rue des Cinquante Otages',
   'line2': None,
   'city': 'Nantes',
   'state': None,
   'country': 'France',
   'postalCode': '44000'}},
 {'number': 121,
  'name': 'Baane Mini Imports',
  'contact': {'lastName': 'Bergulfsen',
   'firstName': 'Jonas ',
   'phone': '07-98 9555'},
  'address': {'line1': 'Erling Skakkes gate 78',
   'line2': None,
   'city': 'Stavern',
   'state': None,
   'country': 'Norway',
   'postalCode': '4110'}},
 {'number': 124,
  'name': 'Mini Gifts Distributors Ltd.',
  'contact': {'lastName': 'Nelson',
   'firstName': 'Susan',
   'phone': '4155551450'},
  'address': {'line1': '5677 Strong St.',
   'line2': None,
   'city': 'San Rafael',
   'state': 'CA',
   'country': 'USA',
   'postalCode': '97562'}},
 {'number': 125,
  'name': 'Havel & Zbyszek Co',
  'contact': {'lastName': 'Piestrzeniewicz',
   'firstName': 'Zbyszek ',
   'phone': '(26) 642-7555'},
  'address': {'line1': 'ul. Filtrowa 68',
   'line2': None,
   'city': 'Warszawa',
   'state': None,
   'country': 'Poland',
   'postalCode': '01-012'}},
 {'number': 128,
  'name': 'Blauer See Auto, Co.',
  'contact': {'lastName': 'Keitel',
   'firstName': 'Roland',
   'phone': '+49 69 66 90 2555'},
  'address': {'line1': 'Lyonerstr. 34',
   'line2': None,
   'city': 'Frankfurt',
   'state': None,
   'country': 'Germany',
   'postalCode': '60528'}},
 {'number': 129,
  'name': 'Mini Wheels Co.',
  'contact': {'lastName': 'Murphy',
   'firstName': 'Julie',
   'phone': '6505555787'},
  'address': {'line1': '5557 North Pendale Street',
   'line2': None,
   'city': 'San Francisco',
   'state': 'CA',
   'country': 'USA',
   'postalCode': '94217'}},
 {'number': 131,
  'name': 'Land of Toys Inc.',
  'contact': {'lastName': 'Lee', 'firstName': 'Kwai', 'phone': '2125557818'},
  'address': {'line1': '897 Long Airport Avenue',
   'line2': None,
   'city': 'NYC',
   'state': 'NY',
   'country': 'USA',
   'postalCode': '10022'}},
 {'number': 141,
  'name': 'Euro+ Shopping Channel',
  'contact': {'lastName': 'Freyre',
   'firstName': 'Diego ',
   'phone': '(91) 555 94 44'},
  'address': {'line1': 'C/ Moralzarzal, 86',
   'line2': None,
   'city': 'Madrid',
   'state': None,
   'country': 'Spain',
   'postalCode': '28034'}},
 {'number': 144,
  'name': 'Volvo Model Replicas, Co',
  'contact': {'lastName': 'Berglund',
   'firstName': 'Christina ',
   'phone': '0921-12 3555'},
  'address': {'line1': 'Berguvsvägen  8',
   'line2': None,
   'city': 'Luleå',
   'state': None,
   'country': 'Sweden',
   'postalCode': 'S-958 22'}},
 {'number': 145,
  'name': 'Danish Wholesale Imports',
  'contact': {'lastName': 'Petersen',
   'firstName': 'Jytte ',
   'phone': '31 12 3555'},
  'address': {'line1': 'Vinbæltet 34',
   'line2': None,
   'city': 'Kobenhavn',
   'state': None,
   'country': 'Denmark',
   'postalCode': '1734'}},
 {'number': 146,
  'name': 'Saveley & Henriot, Co.',
  'contact': {'lastName': 'Saveley',
   'firstName': 'Mary ',
   'phone': '78.32.5555'},
  'address': {'line1': '2, rue du Commerce',
   'line2': None,
   'city': 'Lyon',
   'state': None,
   'country': 'France',
   'postalCode': '69004'}},
 {'number': 148,
  'name': 'Dragon Souveniers, Ltd.',
  'contact': {'lastName': 'Natividad',
   'firstName': 'Eric',
   'phone': '+65 221 7555'},
  'address': {'line1': 'Bronz Sok.',
   'line2': 'Bronz Apt. 3/6 Tesvikiye',
   'city': 'Singapore',
   'state': None,
   'country': 'Singapore',
   'postalCode': '079903'}},
 {'number': 151,
  'name': 'Muscle Machine Inc',
  'contact': {'lastName': 'Young', 'firstName': 'Jeff', 'phone': '2125557413'},
  'address': {'line1': '4092 Furth Circle',
   'line2': 'Suite 400',
   'city': 'NYC',
   'state': 'NY',
   'country': 'USA',
   'postalCode': '10022'}},
 {'number': 157,
  'name': 'Diecast Classics Inc.',
  'contact': {'lastName': 'Leong',
   'firstName': 'Kelvin',
   'phone': '2155551555'},
  'address': {'line1': '7586 Pompton St.',
   'line2': None,
   'city': 'Allentown',
   'state': 'PA',
   'country': 'USA',
   'postalCode': '70267'}},
 {'number': 161,
  'name': 'Technics Stores Inc.',
  'contact': {'lastName': 'Hashimoto',
   'firstName': 'Juri',
   'phone': '6505556809'},
  'address': {'line1': '9408 Furth Circle',
   'line2': None,
   'city': 'Burlingame',
   'state': 'CA',
   'country': 'USA',
   'postalCode': '94217'}},
 {'number': 166,
  'name': 'Handji Gifts& Co',
  'contact': {'lastName': 'Victorino',
   'firstName': 'Wendy',
   'phone': '+65 224 1555'},
  'address': {'line1': '106 Linden Road Sandown',
   'line2': '2nd Floor',
   'city': 'Singapore',
   'state': None,
   'country': 'Singapore',
   'postalCode': '069045'}},
 {'number': 167,
  'name': 'Herkku Gifts',
  'contact': {'lastName': 'Oeztan',
   'firstName': 'Veysel',
   'phone': '+47 2267 3215'},
  'address': {'line1': 'Brehmen St. 121',
   'line2': 'PR 334 Sentrum',
   'city': 'Bergen',
   'state': None,
   'country': 'Norway  ',
   'postalCode': 'N 5804'}},
 {'number': 168,
  'name': 'American Souvenirs Inc',
  'contact': {'lastName': 'Franco',
   'firstName': 'Keith',
   'phone': '2035557845'},
  'address': {'line1': '149 Spinnaker Dr.',
   'line2': 'Suite 101',
   'city': 'New Haven',
   'state': 'CT',
   'country': 'USA',
   'postalCode': '97823'}},
 {'number': 169,
  'name': 'Porto Imports Co.',
  'contact': {'lastName': 'de Castro',
   'firstName': 'Isabel ',
   'phone': '(1) 356-5555'},
  'address': {'line1': 'Estrada da saúde n. 58',
   'line2': None,
   'city': 'Lisboa',
   'state': None,
   'country': 'Portugal',
   'postalCode': '1756'}},
 {'number': 171,
  'name': 'Daedalus Designs Imports',
  'contact': {'lastName': 'Rancé',
   'firstName': 'Martine ',
   'phone': '20.16.1555'},
  'address': {'line1': '184, chaussée de Tournai',
   'line2': None,
   'city': 'Lille',
   'state': None,
   'country': 'France',
   'postalCode': '59000'}},
 {'number': 172,
  'name': "La Corne D'abondance, Co.",
  'contact': {'lastName': 'Bertrand',
   'firstName': 'Marie',
   'phone': '(1) 42.34.2555'},
  'address': {'line1': '265, boulevard Charonne',
   'line2': None,
   'city': 'Paris',
   'state': None,
   'country': 'France',
   'postalCode': '75012'}},
 {'number': 173,
  'name': 'Cambridge Collectables Co.',
  'contact': {'lastName': 'Tseng',
   'firstName': 'Jerry',
   'phone': '6175555555'},
  'address': {'line1': '4658 Baden Av.',
   'line2': None,
   'city': 'Cambridge',
   'state': 'MA',
   'country': 'USA',
   'postalCode': '51247'}},
 {'number': 175,
  'name': 'Gift Depot Inc.',
  'contact': {'lastName': 'King', 'firstName': 'Julie', 'phone': '2035552570'},
  'address': {'line1': '25593 South Bay Ln.',
   'line2': None,
   'city': 'Bridgewater',
   'state': 'CT',
   'country': 'USA',
   'postalCode': '97562'}},
 {'number': 177,
  'name': 'Osaka Souveniers Co.',
  'contact': {'lastName': 'Kentary',
   'firstName': 'Mory',
   'phone': '+81 06 6342 5555'},
  'address': {'line1': '1-6-20 Dojima',
   'line2': None,
   'city': 'Kita-ku',
   'state': 'Osaka',
   'country': 'Japan',
   'postalCode': ' 530-0003'}},
 {'number': 181,
  'name': 'Vitachrome Inc.',
  'contact': {'lastName': 'Frick',
   'firstName': 'Michael',
   'phone': '2125551500'},
  'address': {'line1': '2678 Kingston Rd.',
   'line2': 'Suite 101',
   'city': 'NYC',
   'state': 'NY',
   'country': 'USA',
   'postalCode': '10022'}},
 {'number': 186,
  'name': 'Toys of Finland, Co.',
  'contact': {'lastName': 'Karttunen',
   'firstName': 'Matti',
   'phone': '90-224 8555'},
  'address': {'line1': 'Keskuskatu 45',
   'line2': None,
   'city': 'Helsinki',
   'state': None,
   'country': 'Finland',
   'postalCode': '21240'}},
 {'number': 187,
  'name': 'AV Stores, Co.',
  'contact': {'lastName': 'Ashworth',
   'firstName': 'Rachel',
   'phone': '(171) 555-1555'},
  'address': {'line1': 'Fauntleroy Circus',
   'line2': None,
   'city': 'Manchester',
   'state': None,
   'country': 'UK',
   'postalCode': 'EC2 5NT'}},
 {'number': 189,
  'name': 'Clover Collections, Co.',
  'contact': {'lastName': 'Cassidy',
   'firstName': 'Dean',
   'phone': '+353 1862 1555'},
  'address': {'line1': '25 Maiden Lane',
   'line2': 'Floor No. 4',
   'city': 'Dublin',
   'state': None,
   'country': 'Ireland',
   'postalCode': '2'}},
 {'number': 198,
  'name': 'Auto-Moto Classics Inc.',
  'contact': {'lastName': 'Taylor',
   'firstName': 'Leslie',
   'phone': '6175558428'},
  'address': {'line1': '16780 Pompton St.',
   'line2': None,
   'city': 'Brickhaven',
   'state': 'MA',
   'country': 'USA',
   'postalCode': '58339'}},
 {'number': 201,
  'name': 'UK Collectables, Ltd.',
  'contact': {'lastName': 'Devon',
   'firstName': 'Elizabeth',
   'phone': '(171) 555-2282'},
  'address': {'line1': '12, Berkeley Gardens Blvd',
   'line2': None,
   'city': 'Liverpool',
   'state': None,
   'country': 'UK',
   'postalCode': 'WX1 6LT'}},
 {'number': 202,
  'name': 'Canadian Gift Exchange Network',
  'contact': {'lastName': 'Tamuri',
   'firstName': 'Yoshi ',
   'phone': '(604) 555-3392'},
  'address': {'line1': '1900 Oak St.',
   'line2': None,
   'city': 'Vancouver',
   'state': 'BC',
   'country': 'Canada',
   'postalCode': 'V3F 2K1'}},
 {'number': 204,
  'name': 'Online Mini Collectables',
  'contact': {'lastName': 'Barajas',
   'firstName': 'Miguel',
   'phone': '6175557555'},
  'address': {'line1': '7635 Spinnaker Dr.',
   'line2': None,
   'city': 'Brickhaven',
   'state': 'MA',
   'country': 'USA',
   'postalCode': '58339'}},
 {'number': 205,
  'name': 'Toys4GrownUps.com',
  'contact': {'lastName': 'Young',
   'firstName': 'Julie',
   'phone': '6265557265'},
  'address': {'line1': '78934 Hillside Dr.',
   'line2': None,
   'city': 'Pasadena',
   'state': 'CA',
   'country': 'USA',
   'postalCode': '90003'}},
 {'number': 206,
  'name': 'Asian Shopping Network, Co',
  'contact': {'lastName': 'Walker',
   'firstName': 'Brydey',
   'phone': '+612 9411 1555'},
  'address': {'line1': 'Suntec Tower Three',
   'line2': '8 Temasek',
   'city': 'Singapore',
   'state': None,
   'country': 'Singapore',
   'postalCode': '038988'}},
 {'number': 209,
  'name': 'Mini Caravy',
  'contact': {'lastName': 'Citeaux',
   'firstName': 'Frédérique ',
   'phone': '88.60.1555'},
  'address': {'line1': '24, place Kléber',
   'line2': None,
   'city': 'Strasbourg',
   'state': None,
   'country': 'France',
   'postalCode': '67000'}},
 {'number': 211,
  'name': 'King Kong Collectables, Co.',
  'contact': {'lastName': 'Gao',
   'firstName': 'Mike',
   'phone': '+852 2251 1555'},
  'address': {'line1': 'Bank of China Tower',
   'line2': '1 Garden Road',
   'city': 'Central Hong Kong',
   'state': None,
   'country': 'Hong Kong',
   'postalCode': None}},
 {'number': 216,
  'name': 'Enaco Distributors',
  'contact': {'lastName': 'Saavedra',
   'firstName': 'Eduardo ',
   'phone': '(93) 203 4555'},
  'address': {'line1': 'Rambla de Cataluña, 23',
   'line2': None,
   'city': 'Barcelona',
   'state': None,
   'country': 'Spain',
   'postalCode': '08022'}},
 {'number': 219,
  'name': 'Boards & Toys Co.',
  'contact': {'lastName': 'Young', 'firstName': 'Mary', 'phone': '3105552373'},
  'address': {'line1': '4097 Douglas Av.',
   'line2': None,
   'city': 'Glendale',
   'state': 'CA',
   'country': 'USA',
   'postalCode': '92561'}},
 {'number': 223,
  'name': 'Natürlich Autos',
  'contact': {'lastName': 'Kloss',
   'firstName': 'Horst ',
   'phone': '0372-555188'},
  'address': {'line1': 'Taucherstraße 10',
   'line2': None,
   'city': 'Cunewalde',
   'state': None,
   'country': 'Germany',
   'postalCode': '01307'}},
 {'number': 227,
  'name': 'Heintze Collectables',
  'contact': {'lastName': 'Ibsen',
   'firstName': 'Palle',
   'phone': '86 21 3555'},
  'address': {'line1': 'Smagsloget 45',
   'line2': None,
   'city': 'Århus',
   'state': None,
   'country': 'Denmark',
   'postalCode': '8200'}},
 {'number': 233,
  'name': 'Québec Home Shopping Network',
  'contact': {'lastName': 'Fresnière',
   'firstName': 'Jean ',
   'phone': '(514) 555-8054'},
  'address': {'line1': '43 rue St. Laurent',
   'line2': None,
   'city': 'Montréal',
   'state': 'Québec',
   'country': 'Canada',
   'postalCode': 'H1J 1C3'}},
 {'number': 237,
  'name': 'ANG Resellers',
  'contact': {'lastName': 'Camino',
   'firstName': 'Alejandra ',
   'phone': '(91) 745 6555'},
  'address': {'line1': 'Gran Vía, 1',
   'line2': None,
   'city': 'Madrid',
   'state': None,
   'country': 'Spain',
   'postalCode': '28001'}},
 {'number': 239,
  'name': 'Collectable Mini Designs Co.',
  'contact': {'lastName': 'Thompson',
   'firstName': 'Valarie',
   'phone': '7605558146'},
  'address': {'line1': '361 Furth Circle',
   'line2': None,
   'city': 'San Diego',
   'state': 'CA',
   'country': 'USA',
   'postalCode': '91217'}},
 {'number': 240,
  'name': 'giftsbymail.co.uk',
  'contact': {'lastName': 'Bennett',
   'firstName': 'Helen ',
   'phone': '(198) 555-8888'},
  'address': {'line1': 'Garden House',
   'line2': 'Crowther Way 23',
   'city': 'Cowes',
   'state': 'Isle of Wight',
   'country': 'UK',
   'postalCode': 'PO31 7PJ'}},
 {'number': 242,
  'name': 'Alpha Cognac',
  'contact': {'lastName': 'Roulet',
   'firstName': 'Annette ',
   'phone': '61.77.6555'},
  'address': {'line1': '1 rue Alsace-Lorraine',
   'line2': None,
   'city': 'Toulouse',
   'state': None,
   'country': 'France',
   'postalCode': '31000'}},
 {'number': 247,
  'name': 'Messner Shopping Network',
  'contact': {'lastName': 'Messner',
   'firstName': 'Renate ',
   'phone': '069-0555984'},
  'address': {'line1': 'Magazinweg 7',
   'line2': None,
   'city': 'Frankfurt',
   'state': None,
   'country': 'Germany',
   'postalCode': '60528'}},
 {'number': 249,
  'name': 'Amica Models & Co.',
  'contact': {'lastName': 'Accorti',
   'firstName': 'Paolo ',
   'phone': '011-4988555'},
  'address': {'line1': 'Via Monte Bianco 34',
   'line2': None,
   'city': 'Torino',
   'state': None,
   'country': 'Italy',
   'postalCode': '10100'}},
 {'number': 250,
  'name': 'Lyon Souveniers',
  'contact': {'lastName': 'Da Silva',
   'firstName': 'Daniel',
   'phone': '+33 1 46 62 7555'},
  'address': {'line1': '27 rue du Colonel Pierre Avia',
   'line2': None,
   'city': 'Paris',
   'state': None,
   'country': 'France',
   'postalCode': '75508'}},
 {'number': 256,
  'name': 'Auto Associés & Cie.',
  'contact': {'lastName': 'Tonini',
   'firstName': 'Daniel ',
   'phone': '30.59.8555'},
  'address': {'line1': "67, avenue de l'Europe",
   'line2': None,
   'city': 'Versailles',
   'state': None,
   'country': 'France',
   'postalCode': '78000'}},
 {'number': 259,
  'name': 'Toms Spezialitäten, Ltd',
  'contact': {'lastName': 'Pfalzheim',
   'firstName': 'Henriette ',
   'phone': '0221-5554327'},
  'address': {'line1': 'Mehrheimerstr. 369',
   'line2': None,
   'city': 'Köln',
   'state': None,
   'country': 'Germany',
   'postalCode': '50739'}},
 {'number': 260,
  'name': 'Royal Canadian Collectables, Ltd.',
  'contact': {'lastName': 'Lincoln',
   'firstName': 'Elizabeth ',
   'phone': '(604) 555-4555'},
  'address': {'line1': '23 Tsawassen Blvd.',
   'line2': None,
   'city': 'Tsawassen',
   'state': 'BC',
   'country': 'Canada',
   'postalCode': 'T2F 8M4'}},
 {'number': 273,
  'name': 'Franken Gifts, Co',
  'contact': {'lastName': 'Franken',
   'firstName': 'Peter ',
   'phone': '089-0877555'},
  'address': {'line1': 'Berliner Platz 43',
   'line2': None,
   'city': 'München',
   'state': None,
   'country': 'Germany',
   'postalCode': '80805'}},
 {'number': 276,
  'name': "Anna's Decorations, Ltd",
  'contact': {'lastName': "O'Hara",
   'firstName': 'Anna',
   'phone': '02 9936 8555'},
  'address': {'line1': '201 Miller Street',
   'line2': 'Level 15',
   'city': 'North Sydney',
   'state': 'NSW',
   'country': 'Australia',
   'postalCode': '2060'}},
 {'number': 278,
  'name': 'Rovelli Gifts',
  'contact': {'lastName': 'Rovelli',
   'firstName': 'Giovanni ',
   'phone': '035-640555'},
  'address': {'line1': 'Via Ludovico il Moro 22',
   'line2': None,
   'city': 'Bergamo',
   'state': None,
   'country': 'Italy',
   'postalCode': '24100'}},
 {'number': 282,
  'name': 'Souveniers And Things Co.',
  'contact': {'lastName': 'Huxley',
   'firstName': 'Adrian',
   'phone': '+61 2 9495 8555'},
  'address': {'line1': 'Monitor Money Building',
   'line2': '815 Pacific Hwy',
   'city': 'Chatswood',
   'state': 'NSW',
   'country': 'Australia',
   'postalCode': '2067'}},
 {'number': 286,
  'name': "Marta's Replicas Co.",
  'contact': {'lastName': 'Hernandez',
   'firstName': 'Marta',
   'phone': '6175558555'},
  'address': {'line1': '39323 Spinnaker Dr.',
   'line2': None,
   'city': 'Cambridge',
   'state': 'MA',
   'country': 'USA',
   'postalCode': '51247'}},
 {'number': 293,
  'name': 'BG&E Collectables',
  'contact': {'lastName': 'Harrison',
   'firstName': 'Ed',
   'phone': '+41 26 425 50 01'},
  'address': {'line1': 'Rte des Arsenaux 41 ',
   'line2': None,
   'city': 'Fribourg',
   'state': None,
   'country': 'Switzerland',
   'postalCode': '1700'}},
 {'number': 298,
  'name': 'Vida Sport, Ltd',
  'contact': {'lastName': 'Holz',
   'firstName': 'Mihael',
   'phone': '0897-034555'},
  'address': {'line1': 'Grenzacherweg 237',
   'line2': None,
   'city': 'Genève',
   'state': None,
   'country': 'Switzerland',
   'postalCode': '1203'}},
 {'number': 299,
  'name': 'Norway Gifts By Mail, Co.',
  'contact': {'lastName': 'Klaeboe',
   'firstName': 'Jan',
   'phone': '+47 2212 1555'},
  'address': {'line1': 'Drammensveien 126A',
   'line2': 'PB 211 Sentrum',
   'city': 'Oslo',
   'state': None,
   'country': 'Norway  ',
   'postalCode': 'N 0106'}},
 {'number': 303,
  'name': 'Schuyler Imports',
  'contact': {'lastName': 'Schuyler',
   'firstName': 'Bradley',
   'phone': '+31 20 491 9555'},
  'address': {'line1': 'Kingsfordweg 151',
   'line2': None,
   'city': 'Amsterdam',
   'state': None,
   'country': 'Netherlands',
   'postalCode': '1043 GR'}},
 {'number': 307,
  'name': 'Der Hund Imports',
  'contact': {'lastName': 'Andersen',
   'firstName': 'Mel',
   'phone': '030-0074555'},
  'address': {'line1': 'Obere Str. 57',
   'line2': None,
   'city': 'Berlin',
   'state': None,
   'country': 'Germany',
   'postalCode': '12209'}},
 {'number': 311,
  'name': 'Oulu Toy Supplies, Inc.',
  'contact': {'lastName': 'Koskitalo',
   'firstName': 'Pirkko',
   'phone': '981-443655'},
  'address': {'line1': 'Torikatu 38',
   'line2': None,
   'city': 'Oulu',
   'state': None,
   'country': 'Finland',
   'postalCode': '90110'}},
 {'number': 314,
  'name': 'Petit Auto',
  'contact': {'lastName': 'Dewey',
   'firstName': 'Catherine ',
   'phone': '(02) 5554 67'},
  'address': {'line1': 'Rue Joseph-Bens 532',
   'line2': None,
   'city': 'Bruxelles',
   'state': None,
   'country': 'Belgium',
   'postalCode': 'B-1180'}},
 {'number': 319,
  'name': 'Mini Classics',
  'contact': {'lastName': 'Frick',
   'firstName': 'Steve',
   'phone': '9145554562'},
  'address': {'line1': '3758 North Pendale Street',
   'line2': None,

In [24]:
for c in customers:
    customerNo = c["number"]
    orders = %sql select * from orders where customerNumber=$customerNo
    c["orders"] = []
    
    for o in orders:
        new_o = {
            "number": o["orderNumber"],
            "orderDate": str(o["orderDate"]),
            "requiredDate": str(o["requiredDate"]),
            "shippedDate": str(o["shippedDate"]),
            "status": o["status"]
        }
        c["orders"].append(new_o)

 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
17 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
26 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
0 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.

In [25]:
customers[1]

{'number': 112,
 'name': 'Signal Gift Stores',
 'contact': {'lastName': 'King', 'firstName': 'Jean', 'phone': '7025551838'},
 'address': {'line1': '8489 Strong St.',
  'line2': None,
  'city': 'Las Vegas',
  'state': 'NV',
  'country': 'USA',
  'postalCode': '83030'},
 'orders': [{'number': 10124,
   'orderDate': '2003-05-21',
   'requiredDate': '2003-05-29',
   'shippedDate': '2003-05-25',
   'status': 'Shipped'},
  {'number': 10278,
   'orderDate': '2004-08-06',
   'requiredDate': '2004-08-16',
   'shippedDate': '2004-08-09',
   'status': 'Shipped'},
  {'number': 10346,
   'orderDate': '2004-11-29',
   'requiredDate': '2004-12-05',
   'shippedDate': '2004-11-30',
   'status': 'Shipped'}]}

In [26]:
for c in customers:
    for o in c["orders"]:
        nn = o["number"]
        lines = %sql select * from orderDetails where orderNumber=$nn order by orderLineNumber
        
        o["details"] = []
        
        for l in lines:
            new_l = {
                "lineNumber": l["orderLineNumber"],
                "quantityOrdered": int(l["quantityOrdered"]),
                "priceEach": float(l["priceEach"]),
                "productCode": l["productCode"]
            }
            o["details"].append(new_l)

 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
10 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
15 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
15 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
12 rows affected.
 * mysql+pymysql://root:***@localhost
18 rows affected.
 * mysql+pymysql://root:***@localhost
7 rows affected.
 * mysql+pymysql://root:***@localhost
15 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
16 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
17 rows affected.
 * mysql+pymysql://root:***@localhost
16 rows affected.
 * mysql+pymysql://root:***@localhost
17 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
17 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
10 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
12 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
16 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
7 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
12 rows affected.
 * mysql+pymysql://root:***@localhost
15 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
16 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
16 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
17 rows affected.
 * mysql+pymysql://root:***@localhost
10 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
10 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
18 rows affected.
 * mysql+pymysql://root:***@localhost
7 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
15 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
15 rows affected.
 * mysql+pymysql://root:***@localhost
15 rows affected.
 * mysql+pymysql://root:***@localhost
12 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
18 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
15 rows affected.
 * mysql+pymysql://root:***@localhost
17 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
10 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
18 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
7 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
17 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
10 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
12 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
17 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
16 rows affected.
 * mysql+pymysql://root:***@localhost
17 rows affected.
 * mysql+pymysql://root:***@localhost
18 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
7 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
16 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
12 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
10 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
12 rows affected.
 * mysql+pymysql://root:***@localhost
15 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
18 rows affected.
 * mysql+pymysql://root:***@localhost
7 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
18 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
12 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
17 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
7 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
17 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
17 rows affected.
 * mysql+pymysql://root:***@localhost
12 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
10 rows affected.
 * mysql+pymysql://root:***@localhost
18 rows affected.
 * mysql+pymysql://root:***@localhost
16 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
17 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
10 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
17 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
15 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
10 rows affected.
 * mysql+pymysql://root:***@localhost
16 rows affected.
 * mysql+pymysql://root:***@localhost
16 rows affected.
 * mysql+pymysql://root:***@localhost
16 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
18 rows affected.
 * mysql+pymysql://root:***@localhost
10 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
12 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
12 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost

9 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
15 rows affected.
 * mysql+pymysql://root:***@localhost
12 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
17 rows affected.
 * mysql+pymysql://root:***@localhost
7 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
18 rows affected.
 * mysql+pymysql://root:***@localhost
7 rows affected.
 * mysql+pymysql://root:***@localhost
10 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
7 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
16 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
10 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
16 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
10 rows affected.
 * mysql+pymysql://root:***@localhost
15 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
16 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
15 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
16 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
12 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
1 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
17 rows affected.
 * mysql+pymysql://root:***@localhost
7 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
15 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.
 * mysql+pymysql://root:***@localhost
16 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
5 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
10 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
6 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
14 rows affected.
 * mysql+pymysql://root:***@localhost
11 rows affected.
 * mysql+pymysql://root:***@localhost
4 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
3 rows affected.
 * mysql+pymysql://root:***@localhost
16 rows affected.
 * mysql+pymysql://root:***@localhost
2 rows affected.
 * mysql+pymysql://root:***@localhost
13 rows affected.
 * mysql+pymysql://root:***@localhost
9 rows affected.
 * mysql+pymysql://root:***@localhost
18 rows affected.
 * mysql+pymysql://root:***@localhost
8 rows affected.

In [27]:
import json

In [28]:
print(json.dumps(customers[1], indent=2, default=str))

{
  "number": 112,
  "name": "Signal Gift Stores",
  "contact": {
    "lastName": "King",
    "firstName": "Jean",
    "phone": "7025551838"
  },
  "address": {
    "line1": "8489 Strong St.",
    "line2": null,
    "city": "Las Vegas",
    "state": "NV",
    "country": "USA",
    "postalCode": "83030"
  },
  "orders": [
    {
      "number": 10124,
      "orderDate": "2003-05-21",
      "requiredDate": "2003-05-29",
      "shippedDate": "2003-05-25",
      "status": "Shipped",
      "details": [
        {
          "lineNumber": 1,
          "quantityOrdered": 22,
          "priceEach": 36.29,
          "productCode": "S24_2022"
        },
        {
          "lineNumber": 2,
          "quantityOrdered": 45,
          "priceEach": 30.53,
          "productCode": "S24_1937"
        },
        {
          "lineNumber": 3,
          "quantityOrdered": 42,
          "priceEach": 111.87,
          "productCode": "S18_2325"
        },
        {
          "lineNumber": 4,
          "quantityOrdered": 46,
          "priceEach": 36.11,
          "productCode": "S24_3969"
        },
        {
          "lineNumber": 5,
          "quantityOrdered": 42,
          "priceEach": 58.12,
          "productCode": "S18_2248"
        },
        {
          "lineNumber": 6,
          "quantityOrdered": 21,
          "priceEach": 153.0,
          "productCode": "S18_1749"
        },
        {
          "lineNumber": 7,
          "quantityOrdered": 36,
          "priceEach": 75.46,
          "productCode": "S18_4409"
        },
        {
          "lineNumber": 8,
          "quantityOrdered": 23,
          "priceEach": 66.28,
          "productCode": "S18_4933"
        },
        {
          "lineNumber": 9,
          "quantityOrdered": 25,
          "priceEach": 93.95,
          "productCode": "S24_2887"
        },
        {
          "lineNumber": 10,
          "quantityOrdered": 32,
          "priceEach": 74.51,
          "productCode": "S24_2766"
        },
        {
          "lineNumber": 11,
          "quantityOrdered": 49,
          "priceEach": 76.19,
          "productCode": "S24_3191"
        },
        {
          "lineNumber": 12,
          "quantityOrdered": 22,
          "priceEach": 62.47,
          "productCode": "S24_1046"
        },
        {
          "lineNumber": 13,
          "quantityOrdered": 43,
          "priceEach": 101.73,
          "productCode": "S24_3432"
        }
      ]
    },
    {
      "number": 10278,
      "orderDate": "2004-08-06",
      "requiredDate": "2004-08-16",
      "shippedDate": "2004-08-09",
      "status": "Shipped",
      "details": [
        {
          "lineNumber": 1,
          "quantityOrdered": 35,
          "priceEach": 48.8,
          "productCode": "S24_1628"
        },
        {
          "lineNumber": 2,
          "quantityOrdered": 23,
          "priceEach": 107.02,
          "productCode": "S18_1589"
        },
        {
          "lineNumber": 3,
          "quantityOrdered": 39,
          "priceEach": 117.48,
          "productCode": "S18_2870"
        },
        {
          "lineNumber": 4,
          "quantityOrdered": 31,
          "priceEach": 114.44,
          "productCode": "S18_3685"
        },
        {
          "lineNumber": 5,
          "quantityOrdered": 29,
          "priceEach": 118.07,
          "productCode": "S18_1984"
        },
        {
          "lineNumber": 6,
          "quantityOrdered": 34,
          "priceEach": 114.65,
          "productCode": "S18_1129"
        },
        {
          "lineNumber": 7,
          "quantityOrdered": 42,
          "priceEach": 167.65,
          "productCode": "S18_3232"
        },
        {
          "lineNumber": 8,
          "quantityOrdered": 31,
          "priceEach": 37.38,
          "productCode": "S24_2972"
        },
        {
          "lineNumber": 9,
          "quantityOrdered": 25,
          "priceEach": 136.22,
          "productCode": "S24_3856"
        },
        {
          "lineNumber": 10,
          "quantityOrdered": 29,
          "priceEach": 73.15,
          "productCode": "S18_1889"
        }
      ]
    },
    {
      "number": 10346,
      "orderDate": "2004-11-29",
      "requiredDate": "2004-12-05",
      "shippedDate": "2004-11-30",
      "status": "Shipped",
      "details": [
        {
          "lineNumber": 1,
          "quantityOrdered": 25,
          "priceEach": 87.24,
          "productCode": "S24_2766"
        },
        {
          "lineNumber": 2,
          "quantityOrdered": 24,
          "priceEach": 80.47,
          "productCode": "S24_3191"
        },
        {
          "lineNumber": 3,
          "quantityOrdered": 42,
          "priceEach": 88.36,
          "productCode": "S18_1342"
        },
        {
          "lineNumber": 4,
          "quantityOrdered": 22,
          "priceEach": 38.57,
          "productCode": "S24_3969"
        },
        {
          "lineNumber": 5,
          "quantityOrdered": 24,
          "priceEach": 117.44,
          "productCode": "S24_2887"
        },
        {
          "lineNumber": 6,
          "quantityOrdered": 26,
          "priceEach": 103.87,
          "productCode": "S24_3432"
        }
      ]
    }
  ]
}

In [29]:
print(json.dumps(customers[10], indent=2, default=str))

{
  "number": 141,
  "name": "Euro+ Shopping Channel",
  "contact": {
    "lastName": "Freyre",
    "firstName": "Diego ",
    "phone": "(91) 555 94 44"
  },
  "address": {
    "line1": "C/ Moralzarzal, 86",
    "line2": null,
    "city": "Madrid",
    "state": null,
    "country": "Spain",
    "postalCode": "28034"
  },
  "orders": [
    {
      "number": 10104,
      "orderDate": "2003-01-31",
      "requiredDate": "2003-02-09",
      "shippedDate": "2003-02-01",
      "status": "Shipped",
      "details": [
        {
          "lineNumber": 1,
          "quantityOrdered": 34,
          "priceEach": 131.44,
          "productCode": "S12_3148"
        },
        {
          "lineNumber": 2,
          "quantityOrdered": 32,
          "priceEach": 53.31,
          "productCode": "S50_1514"
        },
        {
          "lineNumber": 3,
          "quantityOrdered": 38,
          "priceEach": 119.2,
          "productCode": "S18_4027"
        },
        {
          "lineNumber": 4,
          "quantityOrdered": 49,
          "priceEach": 56.55,
          "productCode": "S32_3207"
        },
        {
          "lineNumber": 5,
          "quantityOrdered": 26,
          "priceEach": 106.45,
          "productCode": "S24_4048"
        },
        {
          "lineNumber": 6,
          "quantityOrdered": 35,
          "priceEach": 52.02,
          "productCode": "S24_1444"
        },
        {
          "lineNumber": 7,
          "quantityOrdered": 33,
          "priceEach": 114.59,
          "productCode": "S50_1392"
        },
        {
          "lineNumber": 8,
          "quantityOrdered": 24,
          "priceEach": 135.9,
          "productCode": "S18_2238"
        },
        {
          "lineNumber": 9,
          "quantityOrdered": 41,
          "priceEach": 111.39,
          "productCode": "S12_4473"
        },
        {
          "lineNumber": 10,
          "quantityOrdered": 44,
          "priceEach": 30.41,
          "productCode": "S24_2840"
        },
        {
          "lineNumber": 11,
          "quantityOrdered": 35,
          "priceEach": 51.95,
          "productCode": "S32_2509"
        },
        {
          "lineNumber": 12,
          "quantityOrdered": 29,
          "priceEach": 122.73,
          "productCode": "S18_2319"
        },
        {
          "lineNumber": 13,
          "quantityOrdered": 23,
          "priceEach": 165.95,
          "productCode": "S18_3232"
        }
      ]
    },
    {
      "number": 10128,
      "orderDate": "2003-06-06",
      "requiredDate": "2003-06-12",
      "shippedDate": "2003-06-11",
      "status": "Shipped",
      "details": [
        {
          "lineNumber": 1,
          "quantityOrdered": 43,
          "priceEach": 77.24,
          "productCode": "S18_4522"
        },
        {
          "lineNumber": 2,
          "quantityOrdered": 41,
          "priceEach": 120.2,
          "productCode": "S18_3140"
        },
        {
          "lineNumber": 3,
          "quantityOrdered": 32,
          "priceEach": 72.75,
          "productCode": "S700_1938"
        },
        {
          "lineNumber": 4,
          "quantityOrdered": 41,
          "priceEach": 80.67,
          "productCode": "S18_3259"
        }
      ]
    },
    {
      "number": 10133,
      "orderDate": "2003-06-27",
      "requiredDate": "2003-07-04",
      "shippedDate": "2003-07-03",
      "status": "Shipped",
      "details": [
        {
          "lineNumber": 1,
          "quantityOrdered": 23,
          "priceEach": 80.91,
          "productCode": "S32_1374"
        },
        {
          "lineNumber": 2,
          "quantityOrdered": 27,
          "priceEach": 115.09,
          "productCode": "S700_2834"
        },
        {
          "lineNumber": 3,
          "quantityOrdered": 49,
          "priceEach": 80.26,
          "productCode": "S18_2581"
        },
        {
          "lineNumber": 4,
          "quantityOrdered": 46,
          "priceEach": 61.58,
          "productCode": "S24_4278"
        },
        {
          "lineNumber": 5,
          "quantityOrdered": 41,
          "priceEach": 109.42,
          "productCode": "S24_1785"
        },
        {
          "lineNumber": 6,
          "quantityOrdered": 49,
          "priceEach": 67.41,
          "productCode": "S32_4289"
        },
        {
          "lineNumber": 7,
          "quantityOrdered": 27,
          "priceEach": 37.09,
          "productCode": "S50_1341"
        },
        {
          "lineNumber": 8,
          "quantityOrdered": 24,
          "priceEach": 76.73,
          "productCode": "S700_1691"
        }
      ]
    },
    {
      "number": 10153,
      "orderDate": "2003-09-28",
      "requiredDate": "2003-10-05",
      "shippedDate": "2003-10-03",
      "status": "Shipped",
      "details": [
        {
          "lineNumber": 1,
          "quantityOrdered": 43,
          "priceEach": 58.0,
          "productCode": "S700_1138"
        },
        {
          "lineNumber": 2,
          "quantityOrdered": 50,
          "priceEach": 87.15,
          "productCode": "S700_3505"
        },
        {
          "lineNumber": 3,
          "quantityOrdered": 20,
          "priceEach": 85.41,
          "productCode": "S700_3962"
        },
        {
          "lineNumber": 4,
          "quantityOrdered": 50,
          "priceEach": 51.87,
          "productCode": "S72_3212"
        },
        {
          "lineNumber": 5,
          "quantityOrdered": 40,
          "priceEach": 111.83,
          "productCode": "S24_2011"
        },
        {
          "lineNumber": 6,
          "quantityOrdered": 22,
          "priceEach": 82.5,
          "productCode": "S18_4522"
        },
        {
          "lineNumber": 7,
          "quantityOrdered": 31,
          "priceEach": 125.66,
          "productCode": "S18_3140"
        },
        {
          "lineNumber": 8,
          "quantityOrdered": 31,
          "priceEach": 80.55,
          "productCode": "S700_1938"
        },
        {
          "lineNumber": 9,
          "quantityOrdered": 29,
          "priceEach": 82.69,
          "productCode": "S18_3259"
        },
        {
          "lineNumber": 10,
          "quantityOrdered": 49,
          "priceEach": 155.72,
          "productCode": "S12_3891"
        },
        {
          "lineNumber": 11,
          "quantityOrdered": 20,
          "priceEach": 201.57,
          "productCode": "S12_1108"
        },
        {
          "lineNumber": 12,
          "quantityOrdered": 42,
          "priceEach": 128.42,
          "productCode": "S12_3148"
        },
        {
          "lineNumber": 13,
          "quantityOrdered": 31,
          "priceEach": 53.31,
          "productCode": "S50_1514"
        }
      ]
    },
    {
      "number": 10156,
      "orderDate": "2003-10-08",
      "requiredDate": "2003-10-17",
      "shippedDate": "2003-10-11",
      "status": "Shipped",
      "details": [
        {
          "lineNumber": 1,
          "quantityOrdered": 20,
          "priceEach": 43.64,
          "productCode": "S50_1341"
        },
        {
          "lineNumber": 2,
          "quantityOrdered": 48,
          "priceEach": 77.64,
          "productCode": "S700_1691"
        }
      ]
    },
    {
      "number": 10190,
      "orderDate": "2003-11-19",
      "requiredDate": "2003-11-29",
      "shippedDate": "2003-11-20",
      "status": "Shipped",
      "details": [
        {
          "lineNumber": 1,
          "quantityOrdered": 46,
          "priceEach": 38.62,
          "productCode": "S32_2206"
        },
        {
          "lineNumber": 2,
          "quantityOrdered": 40,
          "priceEach": 67.53,
          "productCode": "S50_4713"
        },
        {
          "lineNumber": 3,
          "quantityOrdered": 42,
          "priceEach": 58.87,
          "productCode": "S24_2360"
        },
        {
          "lineNumber": 4,
          "quantityOrdered": 42,
          "priceEach": 89.8,
          "productCode": "S32_4485"
        }
      ]
    },
    {
      "number": 10203,
      "orderDate": "2003-12-02",
      "requiredDate": "2003-12-11",
      "shippedDate": "2003-12-07",
      "status": "Shipped",
      "details": [
        {
          "lineNumber": 1,
          "quantityOrdered": 48,
          "priceEach": 157.49,
          "productCode": "S18_3232"
        },
        {
          "lineNumber": 2,
          "quantityOrdered": 21,
          "priceEach": 33.23,
          "productCode": "S24_2972"
        },
        {
          "lineNumber": 3,
          "quantityOrdered": 47,
          "priceEach": 140.43,
          "productCode": "S24_3856"
        },
        {
          "lineNumber": 4,
          "quantityOrdered": 45,
          "priceEach": 73.15,
          "productCode": "S18_1889"
        },
        {
          "lineNumber": 5,
          "quantityOrdered": 47,
          "priceEach": 115.16,
          "productCode": "S12_4675"
        },
        {
          "lineNumber": 6,
          "quantityOrdered": 20,
          "priceEach": 111.57,
          "productCode": "S12_3380"
        },
        {
          "lineNumber": 7,
          "quantityOrdered": 34,
          "priceEach": 56.94,
          "productCode": "S24_3371"
        },
        {
          "lineNumber": 8,
          "quantityOrdered": 20,
          "priceEach": 161.49,
          "productCode": "S12_1099"
        },
        {
          "lineNumber": 9,
          "quantityOrdered": 44,
          "priceEach": 63.84,
          "productCode": "S12_3990"
        },
        {
          "lineNumber": 10,
          "quantityOrdered": 32,
          "priceEach": 127.88,
          "productCode": "S18_3482"
        },
        {
          "lineNumber": 11,
          "quantityOrdered": 33,
          "priceEach": 66.74,
          "productCode": "S18_3278"
        }
      ]
    },
    {
      "number": 10205,
      "orderDate": "2003-12-03",
      "requiredDate": "2003-12-09",
      "shippedDate": "2003-12-07",
      "status": "Shipped",
      "details": [
        {
          "lineNumber": 1,
          "quantityOrdered": 48,
          "priceEach": 45.82,
          "productCode": "S18_1367"
        },
        {
          "lineNumber": 2,
          "quantityOrdered": 36,
          "priceEach": 98.63,
          "productCode": "S18_1342"
        },
        {
          "lineNumber": 3,
          "quantityOrdered": 40,
          "priceEach": 138.38,
          "productCode": "S18_2795"
        },
        {
          "lineNumber": 4,
          "quantityOrdered": 24,
          "priceEach": 36.74,
          "productCode": "S24_2022"
        },
        {
          "lineNumber": 5,
          "quantityOrdered": 32,
          "priceEach": 27.88,
          "productCode": "S24_1937"
        }
      ]
    },
    {
      "number": 10212,
      "orderDate": "2004-01-16",
      "requiredDate": "2004-01-24",
      "shippedDate": "2004-01-18",
      "status": "Shipped",
      "details": [
        {
          "lineNumber": 1,
          "quantityOrdered": 45,
          "priceEach": 81.78,
          "productCode": "S24_2766"
        },
        {
          "lineNumber": 2,
          "quantityOrdered": 27,
          "priceEach": 77.91,
          "productCode": "S24_3191"
        },
        {
          "lineNumber": 3,
          "quantityOrdered": 41,
          "priceEach": 61.73,
          "productCode": "S24_1046"
        },
        {
          "lineNumber": 4,
          "quantityOrdered": 46,
          "priceEach": 100.66,
          "productCode": "S24_3432"
        },
        {
          "lineNumber": 5,
          "quantityOrdered": 45,
          "priceEach": 43.27,
          "productCode": "S24_1628"
        },
        {
          "lineNumber": 6,
          "quantityOrdered": 38,
          "priceEach": 105.77,
          "productCode": "S18_1589"
        },
        {
          "lineNumber": 7,
          "quantityOrdered": 40,
          "priceEach": 117.48,
          "productCode": "S18_2870"
        },
        {
          "lineNumber": 8,
          "quantityOrdered": 45,
          "priceEach": 115.85,
          "productCode": "S18_3685"
        },
        {
          "lineNumber": 9,
          "quantityOrdered": 41,
          "priceEach": 133.72,
          "productCode": "S18_1984"
        },
        {
          "lineNumber": 10,
          "quantityOrdered": 29,
          "priceEach": 117.48,
          "productCode": "S18_1129"
        },
        {
          "lineNumber": 11,
          "quantityOrdered": 40,
          "priceEach": 155.79,
          "productCode": "S18_3232"
        },
        {
          "lineNumber": 12,
          "quantityOrdered": 34,
          "priceEach": 37.38,
          "productCode": "S24_2972"
        },
        {
          "lineNumber": 13,
          "quantityOrdered": 49,
          "priceEach": 117.96,
          "productCode": "S24_3856"
        },
        {
          "lineNumber": 14,
          "quantityOrdered": 20,
          "priceEach": 64.68,
          "productCode": "S18_1889"
        },
        {
          "lineNumber": 15,
          "quantityOrdered": 33,
          "priceEach": 110.55,
          "productCode": "S12_4675"
        },
        {
          "lineNumber": 16,
          "quantityOrdered": 39,
          "priceEach": 99.82,
          "productCode": "S12_3380"
        }
      ]
    },
    {
      "number": 10244,
      "orderDate": "2004-04-29",
      "requiredDate": "2004-05-09",
      "shippedDate": "2004-05-04",
      "status": "Shipped",
      "details": [
        {
          "lineNumber": 1,
          "quantityOrdered": 30,
          "priceEach": 87.13,
          "productCode": "S18_2949"
        },
        {
          "lineNumber": 2,
          "quantityOrdered": 29,
          "priceEach": 85.87,
          "productCode": "S18_3136"
        },
        {
          "lineNumber": 3,
          "quantityOrdered": 24,
          "priceEach": 54.96,
          "productCode": "S18_2957"
        },
        {
          "lineNumber": 4,
          "quantityOrdered": 40,
          "priceEach": 97.39,
          "productCode": "S24_4258"
        },
        {
          "lineNumber": 5,
          "quantityOrdered": 36,
          "priceEach": 87.3,
          "productCode": "S18_3320"
        },
        {
          "lineNumber": 6,
          "quantityOrdered": 20,
          "priceEach": 48.52,
          "productCode": "S18_1367"
        },
        {
          "lineNumber": 7,
          "quantityOrdered": 40,
          "priceEach": 99.66,
          "productCode": "S18_1342"
        },
        {
          "lineNumber": 8,
          "quantityOrdered": 43,
          "priceEach": 141.75,
          "productCode": "S18_2795"
        },
        {
          "lineNumber": 9,
          "quantityOrdered": 39,
          "priceEach": 42.11,
          "productCode": "S24_2022"
        }
      ]
    },
    {
      "number": 10246,
      "orderDate": "2004-05-05",
      "requiredDate": "2004-05-13",
      "shippedDate": "2004-05-06",
      "status": "Shipped",
      "details": [
        {
          "lineNumber": 1,
          "quantityOrdered": 46,
          "priceEach": 100.54,
          "productCode": "S24_4048"
        },
        {
          "lineNumber": 2,
          "quantityOrdered": 44,
          "priceEach": 46.24,
          "productCode": "S24_1444"
        },
        {
          "lineNumber": 3,
          "quantityOrdered": 22,
          "priceEach": 113.44,
          "productCode": "S50_1392"
        },
        {
          "lineNumber": 4,
          "quantityOrdered": 40,
          "priceEach": 144.08,
          "productCode": "S18_2238"
        },
        {
          "lineNumber": 5,
          "quantityOrdered": 46,
          "priceEach": 99.54,
          "productCode": "S12_4473"
        },
        {
          "lineNumber": 6,
          "quantityOrdered": 49,
          "priceEach": 34.65,
          "productCode": "S24_2840"
        },
        {
          "lineNumber": 7,
          "quantityOrdered": 35,
          "priceEach": 45.45,
          "productCode": "S32_2509"
        },
        {
          "lineNumber": 8,
          "quantityOrdered": 22,
          "priceEach": 100.64,
          "productCode": "S18_2319"
        },
        {
          "lineNumber": 9,
          "quantityOrdered": 36,
          "priceEach": 145.63,
          "productCode": "S18_3232"
        },
        {
          "lineNumber": 10,
          "quantityOrdered": 29,
          "priceEach": 118.84,
          "productCode": "S24_2300"
        },
        {
          "lineNumber": 11,
          "quantityOrdered": 30,
          "priceEach": 57.73,
          "productCode": "S18_2432"
        }
      ]
    },
    {
      "number": 10262,
      "orderDate": "2004-06-24",
      "requiredDate": "2004-07-01",
      "shippedDate": "None",
      "status": "Cancelled",
      "details": [
        {
          "lineNumber": 1,
          "quantityOrdered": 34,
          "priceEach": 98.48,
          "productCode": "S24_1785"
        },
        {
          "lineNumber": 2,
          "quantityOrdered": 40,
          "priceEach": 63.97,
          "productCode": "S32_4289"
        },
        {
          "lineNumber": 3,
          "quantityOrdered": 49,
          "priceEach": 35.78,
          "productCode": "S50_1341"
        },
        {
          "lineNumber": 4,
          "quantityOrdered": 40,
          "priceEach": 87.69,
          "productCode": "S700_1691"
        },
        {
          "lineNumber": 5,
          "quantityOrdered": 27,
          "priceEach": 64.8,
          "productCode": "S700_3167"
        },
        {
          "lineNumber": 6,
          "quantityOrdered": 33,
          "priceEach": 81.77,
          "productCode": "S700_2466"
        },
        {
          "lineNumber": 7,
          "quantityOrdered": 35,
          "priceEach": 64.41,
          "productCode": "S700_4002"
        },
        {
          "lineNumber": 8,
          "quantityOrdered": 48,
          "priceEach": 58.69,
          "productCode": "S24_3949"
        },
        {
          "lineNumber": 9,
          "quantityOrdered": 49,
          "priceEach": 157.69,
          "productCode": "S18_1662"
        },
        {
          "lineNumber": 10,
          "quantityOrdered": 24,
          "priceEach": 63.71,
          "productCode": "S24_2841"
        },
        {
          "lineNumber": 11,
          "quantityOrdered": 46,
          "priceEach": 65.75,
          "productCode": "S24_3420"
        },
        {
          "lineNumber": 12,
          "quantityOrdered": 21,
          "priceEach": 41.71,
          "productCode": "S72_1253"
        },
        {
          "lineNumber": 13,
          "quantityOrdered": 44,
          "priceEach": 83.28,
          "productCode": "S700_2047"
        },
        {
          "lineNumber": 14,
          "quantityOrdered": 34,
          "priceEach": 85.75,
          "productCode": "S18_3856"
        },
        {
          "lineNumber": 15,
          "quantityOrdered": 32,
          "priceEach": 81.72,
          "productCode": "S18_3029"
        },
        {
          "lineNumber": 16,
          "quantityOrdered": 49,
          "priceEach": 82.18,
          "productCode": "S24_3816"
        }
      ]
    },
    {
      "number": 10279,
      "orderDate": "2004-08-09",
      "requiredDate": "2004-08-19",
      "shippedDate": "2004-08-15",
      "status": "Shipped",
      "details": [
        {
          "lineNumber": 1,
          "quantityOrdered": 26,
          "priceEach": 68.42,
          "productCode": "S18_4933"
        },
        {
          "lineNumber": 2,
          "quantityOrdered": 48,
          "priceEach": 106.87,
          "productCode": "S24_2887"
        },
        {
          "lineNumber": 3,
          "quantityOrdered": 49,
          "priceEach": 76.33,
          "productCode": "S24_2766"
        },
        {
          "lineNumber": 4,
          "quantityOrdered": 33,
          "priceEach": 78.76,
          "productCode": "S24_3191"
        },
        {
          "lineNumber": 5,

- If only I had a database in which I could store the array of documents?

## MongodDB

### Load Data from SQL

In [1]:
import pymongo

In [2]:
secrets_path = "/Users/donaldferguson/Dropbox/00Spring2023/Intro_to_Databases_S23/DONOTSHARE"

In [3]:
import sys

In [4]:
sys.path.append(secrets_path)

In [6]:
client = pymongo.MongoClient()
db = client.test

In [30]:
client["Classic_Models"]["Customers"].drop()

In [31]:
for c in customers:
    client["Classic_Models"]["Customers"].insert_one(c)

- Umm, maybe that stored something. Can I get i back?

In [32]:
client["Classic_Models"]["Customers"].find_one(
    {
        "number": 103
    }
)

#
# select * from s23_classic_models.customers where number=103

{'_id': ObjectId('65e99d5c42ce3ebd449a34b9'),
 'number': 103,
 'name': 'Atelier graphique',
 'contact': {'lastName': 'Schmitt',
  'firstName': 'Carine ',
  'phone': '40.32.2555'},
 'address': {'line1': '54, rue Royale',
  'line2': None,
  'city': 'Nantes',
  'state': None,
  'country': 'France',
  'postalCode': '44000'},
 'orders': [{'number': 10123,
   'orderDate': '2003-05-20',
   'requiredDate': '2003-05-29',
   'shippedDate': '2003-05-22',
   'status': 'Shipped',
   'details': [{'lineNumber': 1,
     'quantityOrdered': 50,
     'priceEach': 43.27,
     'productCode': 'S24_1628'},
    {'lineNumber': 2,
     'quantityOrdered': 26,
     'priceEach': 120.71,
     'productCode': 'S18_1589'},
    {'lineNumber': 3,
     'quantityOrdered': 46,
     'priceEach': 114.84,
     'productCode': 'S18_2870'},
    {'lineNumber': 4,
     'quantityOrdered': 34,
     'priceEach': 117.26,
     'productCode': 'S18_3685'}]},
  {'number': 10298,
   'orderDate': '2004-09-27',
   'requiredDate': '2004-10-05',
   'shippedDate': '2004-10-01',
   'status': 'Shipped',
   'details': [{'lineNumber': 1,
     'quantityOrdered': 39,
     'priceEach': 105.86,
     'productCode': 'S10_2016'},
    {'lineNumber': 2,
     'quantityOrdered': 32,
     'priceEach': 60.57,
     'productCode': 'S18_2625'}]},
  {'number': 10345,
   'orderDate': '2004-11-25',
   'requiredDate': '2004-12-01',
   'shippedDate': '2004-11-26',
   'status': 'Shipped',
   'details': [{'lineNumber': 1,
     'quantityOrdered': 43,
     'priceEach': 38.98,
     'productCode': 'S24_2022'}]}]}

- __Professor Ferguson, That was some serious wizard stuff you just did.__

- Back to the slides ... ...

### Game of Thrones -- Episodes

#### Introduction

- The subdirectory ```data/GoT``` contains Game of Thrones data from a Game of Thrones [data visualization project.](https://jeffreylancaster.com/game-of-thrones/)

In [ ]:
import os.path
import json

In [ ]:
project_dir = "/Users/donaldferguson/Dropbox/00Spring2023/Intro_to_Databases_S23"
got_data_dir = os.path.join(project_dir, "data", "GoT")

In [ ]:
os.listdir(got_data_dir)

- We can load the data by reading the file.

In [ ]:
episodes_file_name = os.path.join(got_data_dir, 'episodes.json')

with open(episodes_file_name, "r") as in_file:
    episode_info = json.load(in_file)

In [ ]:
episode_info

- The list of episode information is wrapped in a single element ```episodes.```


- We want to save the ```list``` of episodes to MongoDB.

In [ ]:
episodes = episode_info['episodes']

In [ ]:
episodes[2]

In [ ]:
result = client['S23_GoT']['Episodes'].insert_many(episodes)

In [ ]:
result

In [ ]:
result.acknowledged

In [ ]:
result.inserted_ids

In [ ]:
len(result.inserted_ids)

- We are going to use a cloud/SaaS free version of MongoDB: [MongoDB Atlas](https://www.mongodb.com/atlas/database)


- I will provide setup instructions and record a video.


- For this lecture, I am going to use my local installation.

<img src="./compass.jpg">

#### Some Basic Queries

- Get episode 1 from season 2.

In [ ]:
filter = {
    "seasonNum": 2,
    "episodeNum": 1
}

In [ ]:
res = client["S23_GoT"]["Episodes"].find(filter)

In [ ]:
# We get back a "cursor" much like pymysql
#
res

In [ ]:
result = list(res)

In [ ]:
result

- That got back the whole document, including all of the embedded documents.


- I can also do a project.

In [ ]:
# Simplify typing Python by getting a reference to the collection object.
episodes_db = client['S23_GoT']['Episodes']
episodes_db

In [ ]:
# The simple where clause
#
f = {
    "seasonNum": 2
}

# A simple projection, aka SELECT c1, c2, ...
#
p = {
    "seasonNum": 1,
    "episodeNum": 1,
    "episodeTitle": 1,
    "episodeDescription": 1,
    "episodeAirDate": 1,
    "jibberish": 1,
    "_id": 0
}

res = episodes_db.find(f, p)
result = list(res)

- You will note that it DID NOT complain about the missing columns ```jibberish.``` Most NoSQL databases have a flexible schema, meaning it is not predefined. The project is OK because there is no ```jibberish``` column.


- Also, I got rid of the automatic UUID.

In [ ]:
result

- This is table like, so I can use Pandas.

In [ ]:
result_df = pandas.DataFrame(result)

In [ ]:
result_df

#### More Complicated Queries

- For more complicated queries, MongoDB uses [aggregation pipelines.](https://www.mongodb.com/docs/manual/core/aggregation-pipeline/)
    - A pipeline is an array of operators.
    - Each operator is declarative.
    
    
- __Note:__ Show building pipelines in the Compass console.

- How many scenes are in each episode?

In [ ]:
scene_info = client['S23_GoT']['Episodes'].aggregate([
    {
        '$project': {
            'seasonNum': 1, 
            'episodeNum': 1, 
            'episodeTitle': 1, 
            'sceneCount': {
                '$size': '$scenes'
            }
        }
    }
])
scene_info = list(scene_info)
scene_df = pandas.DataFrame(scene_info)
scene_df

#### Unwind

- Sometimes "flattening" makes queries easier. This is called ```unwind.```


- Some notes on ```project:```
    - Like SQL, we can transform, rename, compute, ... ... "columns."
    - But, we can also reach __into__ embedded objects.

In [ ]:
result = client['S23_GoT']['Episodes'].aggregate([
    {
        '$unwind': {
            'path': '$scenes', 
            'includeArrayIndex': 'sceneNum', 
            'preserveNullAndEmptyArrays': False
        }
    }, {
        '$match': {
            'scenes.location': 'The Wall', 
            'scenes.subLocation': 'Castle Black'
        }
    }, {
        '$project': {
            'seasonNum': 1, 
            'episodeNum': 1, 
            'episodeTitle': 1, 
            'sceneNum': {
                '$add': [
                    '$sceneNum', 1
                ]
            }, 
            'sceneLocation': '$scenes.location', 
            'sceneSubLocation': '$scenes.subLocation'
        }
    }
])
result = list(result)
result_df = pandas.DataFrame(result)
result_df

In [ ]:
# Requires the PyMongo package.
# https://api.mongodb.com/python/current

result = client['S22_GoT']['episodes'].aggregate([
    {
        '$unwind': {
            'path': '$scenes', 
            'includeArrayIndex': 'sceneNumer', 
            'preserveNullAndEmptyArrays': True
        }
    }, {
        '$match': {
            'seasonNum': 1
        }
    }
])

In [ ]:
list(result)

#### Summary

- We will not become as expert with MongoDB operations as SQL.


- Basic understanding of DocumentDB and concepts is useful.


- The only way to get good is to practice.